#!/bin/sh
SRC="src" # source directory
BUILD="build" # build directory
INSTALL="/usr/local/bin" # install dir
CFLAGS="-g" # c flags
LDFLAGS="-o $BUILD/bfc" # ld flags
CFILES=("main.c" 
	"compiler.c" 
	"lexer.c" 
	"parser.c" 
	"interpreter.c" 
	"global.c") # c files

compile() {
  ls $BUILD &>/dev/null || mkdir $BUILD
  GCCFILES=""
  for CFILE in $CFILES
    GCCFILES+="$SRC/$CFILE "
  done
  gcc $CFLAGS $GCCFILES $LDFLAGS
}
install() {
  [ -f "$0" ] && INSTALL=$0
  ls build/bfc || echo "[compile] No binary of bfc found in $BUILD directory" 
  install build/bfc $INSTALL_DIR
}
case $1 in
  "install" | "i" )
     install $1 ;;
  "compile" | "c" | *)
     compile ;;  
esac
